import type { Movie } from '../types'

const gradients = ['from-[#7759e9] to-[#31c9ed]', 'from-[#ed6678] to-[#f6b665]', 'from-[#08a992] to-[#6959dc]', 'from-[#2866cc] to-[#5ed8f4]', 'from-[#e46ba7] to-[#805bea]', 'from-[#29b987] to-[#087d73]']

type Props = { movie: Movie; index: number; isWatchlisted: boolean; isWatched: boolean; onWatched: () => void; onToggleWatchlist: () => void; onRate: (rating: number) => void }

export default function MovieCard({ movie, index, isWatchlisted, isWatched, onWatched, onToggleWatchlist, onRate }: Props) {
  const initials = movie.title.split(' ').slice(0, 2).map((word) => word[0]).join('').toUpperCase()
  return <article className="animate-[card-in_.45s_ease_forwards] overflow-hidden rounded-[19px] border border-white/10 bg-[#121926]/85 opacity-0 shadow-xl shadow-black/15 transition duration-200 hover:-translate-y-1 hover:border-[#8066ff]/45 hover:shadow-2xl" style={{ animationDelay: `${index * 45}ms` }}>
    <div className={`relative grid h-[250px] place-items-center overflow-hidden bg-gradient-to-br ${gradients[movie.movie_id % gradients.length]} text-[2.4rem] font-bold tracking-[.06em] text-white/95`}>
      {movie.poster_url ? <img src={movie.poster_url} alt="" className="absolute z-[1] h-full w-full object-cover" /> : <span className="relative z-[2] font-['Space_Grotesk']">{initials}</span>}
      <div className="absolute inset-0 z-[2] bg-gradient-to-b from-white/[.08] to-black/25" /><span className="absolute bottom-3 right-3 z-[3] rounded-full bg-[#080d17]/75 px-2.5 py-1.5 text-xs font-semibold tracking-normal text-[#ffe6a1]">★ {movie.vote.toFixed(1)}</span>
    </div>
    <div className="p-4"><div className="flex justify-between gap-2"><span className="text-[.7rem] uppercase tracking-[.06em] text-[#bcb0ff]">{movie.genre || 'Feature film'}</span><span className="text-xs text-[#8696bb]">{movie.release_date?.slice(-4) || '—'}</span></div><h3 className="mt-2 font-['Space_Grotesk'] text-base font-semibold text-[#edf2ff]">{movie.title}</h3>{movie.reason && <p className="mt-3 min-h-9 text-xs leading-relaxed text-[#c8bfff]">{movie.reason}</p>}<div className="mt-3.5 flex items-center gap-2"><button className={`h-8 w-9 rounded-[10px] border border-white/10 bg-white/[.05] text-[#dce5ff] transition hover:border-green-500/50 hover:bg-green-500/20 ${isWatched ? 'border-green-500/50 bg-green-500/20 text-green-400' : 'hover:border-[#8066ff]/50 hover:bg-[#8066ff]/20'}`} onClick={onWatched} title="Mark as watched">✓</button><button className={`h-8 w-9 rounded-[10px] border border-white/10 bg-white/[.05] text-[#dce5ff] transition hover:border-[#8066ff]/50 hover:bg-[#8066ff]/20 ${isWatchlisted ? 'border-[#8066ff]/50 bg-[#8066ff]/20 text-white' : ''}`} onClick={onToggleWatchlist} title="Toggle watchlist">{isWatchlisted ? '♥' : '♡'}</button><select className="ml-auto rounded-[10px] border border-white/10 bg-white/[.05] px-2 py-1.5 text-xs text-[#aebbd7] outline-none" defaultValue="" onChange={(event) => onRate(Number(event.target.value))} aria-label={`Rate ${movie.title}`}><option value="" disabled>Rate</option>{[1, 2, 3, 4, 5].map((rating) => <option value={rating} key={rating}>{rating} / 5</option>)}</select></div></div>
  </article>
}
